name: 'AzureBicepDeploy'
 
on:
  workflow_dispatch:

  push:
    branches:
    - workflow-new

  pull_request:
    branches:
    - main
    paths:
    - 'reference-implementations/AppGW-IAPIM-Func/**'
 
jobs:
  validate_bicep:
    name: "Validate Bicep files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./reference-implementations/AppGW-IAPIM-Func/bicep

  build-and-deploy:
      runs-on: ubuntu-latest
      needs: validate_bicep

      steps:

        # Checkout code
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Install yq to parse yaml file
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
    
      - name: Parse config.yaml as output to GitHub Actions matrix
        run: |
          echo "config=$(yq e ./reference-implementations/AppGW-IAPIM-Func/bicep/config.yml -j -I=0)" >> $GITHUB_ENV  
  
      - name: Write deployment information to log
        run: |
          echo "Deploying to ${{ fromJson(env.config).canadacentral }} with name prefix ${{ fromJson(env.config).abs }} and environment tag ${{ fromJson(env.config).dev }}"
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Preflight Validation
        working-directory: ./reference-implementations/AppGW-IAPIM-Func/bicep
        run: |
            az deployment sub validate \
              --location ${{ fromJson(env.config).canadacentral }} \
              --parameters workloadName=${{ fromJson(env.config).abs }} environment=${{ fromJson(env.config).dev }} \
              vmUsername=${{ fromJson(env.config).abhinab }} vmPassword=${{ secrets.VM_PW }} accountName=${{ secrets.none }} \
              personalAccessToken=${{ secrets.PAT }} CICDAgentType=${{ fromJson(env.config).none}} appGatewayFqdn=${{ secrets.FQDN }} \
              certificatePassword=${{ secrets.CERTPW}} appGatewayCertType=${{ fromJson(env.config).selfsigned }} \
              --template-file main.bicep
 
        # Deploy Bicep file, need to point parameters to the main.parameters.json location
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ fromJson(env.config).canadacentral }}
          template: ./reference-implementations/AppGW-IAPIM-Func/bicep/main.bicep
          parameters: > 
            workloadName=${{ fromJson(env.config).abs }} environment=${{ fromJson(env.config).dev }} 
            vmUsername=${{ fromJson(env.config).abhinab }} vmPassword=${{ secrets.VM_PW }} 
            accountName=${{ secrets.none }} personalAccessToken=${{ secrets.PAT }} CICDAgentType=${{ fromJson(env.config).none}}
            appGatewayFqdn=${{ secrets.FQDN }} certificatePassword=${{ secrets.CERTPW }} appGatewayCertType=${{ fromJson(env.config).selfsigned }}

  Generate-ARM:
    name: "Generate ARM Template"
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Exporting ARM template from the bicep file
      - name: Export ARM template
        working-directory: ./reference-implementations/AppGW-IAPIM-Func/bicep
        run : |
          pwd
          az bicep build --file main.bicep --outfile ../azure-resource-manager/apim-arm.json
          ls -al

      # Uploading exported ARM template to GitHub's artifact 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: apim-arm
          path: /reference-implementations/AppGW-IAPIM-Func/azure-resource-manager/apim-arm.json
          retention-days: 2

      # Committing and pushing exported ARM template to the same repo.
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: APIM-Action
          author_email: abhinab.sarkar@microsoft.com
          message: 'ARM template updated'
          cwd: '/reference-implementations/AppGW-IAPIM-Func/azure-resource-manager/'
          branch_mode: create
          branch: 'arm-${{github.run_number}}'
          add: 'apim-arm.json'
